In [278]:
import pandas as pd
import numpy as np

In [279]:
# Load the dataset
df = pd.read_csv("../data/pollofpolls.csv", sep=";")

In [280]:
df["Mnd"] = df["Mnd"].astype(str)

In [281]:
df.head()

            Mnd    Ap  Hoyre   Frp   SV   Sp  KrF  Venstre  MDG  Rodt  Andre
0     Januar-25  19.1   22.2  24.1  8.0  5.9  3.4      4.5  3.3   5.6    3.9
1   Desember-24  17.2   21.2  25.4  9.4  5.3  3.9      5.3  3.1   5.8    3.5
2   November-24  18.7   22.4  22.0  9.0  6.6  3.1      5.1  3.4   5.9    3.8
3    Oktober-24  19.9   23.4  20.3  8.8  5.8  3.3      5.5  3.5   5.9    3.7
4  September-24  20.6   24.6  18.9  9.0  6.0  2.9      5.1  3.3   5.6    3.9

In [282]:
# Define the lag and trend periods
lags = [1]  # Previous month
trends = [3, 6]  # 3-month, 6-month, and 12-month trends

In [283]:
df_features = df

In [284]:
df_features.head()

            Mnd    Ap  Hoyre   Frp   SV   Sp  KrF  Venstre  MDG  Rodt  Andre
0     Januar-25  19.1   22.2  24.1  8.0  5.9  3.4      4.5  3.3   5.6    3.9
1   Desember-24  17.2   21.2  25.4  9.4  5.3  3.9      5.3  3.1   5.8    3.5
2   November-24  18.7   22.4  22.0  9.0  6.6  3.1      5.1  3.4   5.9    3.8
3    Oktober-24  19.9   23.4  20.3  8.8  5.8  3.3      5.5  3.5   5.9    3.7
4  September-24  20.6   24.6  18.9  9.0  6.0  2.9      5.1  3.3   5.6    3.9

In [285]:
for party in ['Ap', 'Hoyre', 'Frp', 'SV', 'Sp', 'KrF', 'Venstre', 'MDG','Rodt', 'Andre']: 
    df_features[f"{party}_prev"] = df[party].shift(-1)
    for t in trends:
        df_features[f"{party}_trend_{t}"] = df[party].shift(-1) - df[party].shift(-t-1)

In [286]:
df_features.dropna(inplace=True)

In [287]:
df_features.head()

,Mnd,Ap,Hoyre,Frp,SV,Sp,KrF,Venstre,MDG,Rodt,...,Venstre_trend_6,MDG_prev,MDG_trend_3,MDG_trend_6,Rodt_prev,Rodt_trend_3,Rodt_trend_6,Andre_prev,Andre_trend_3,Andre_trend_6
0,Januar-25,19.1,22.2,24.1,8.0,5.9,3.4,4.5,3.3,5.6,...,-0.6,3.1,-0.2,-0.3,5.8,0.2,-0.8,3.5,-0.4,0.0
1,Desember-24,17.2,21.2,25.4,9.4,5.3,3.9,5.3,3.1,5.8,...,-0.8,3.4,-0.2,-0.3,5.9,0.2,0.9,3.8,-0.4,0.0
2,November-24,18.7,22.4,22.0,9.0,6.6,3.1,5.1,3.4,5.9,...,0.0,3.5,-0.2,-0.1,5.9,0.5,0.4,3.7,-1.0,-0.5
3,Oktober-24,19.9,23.4,20.3,8.8,5.8,3.3,5.5,3.5,5.9,...,-0.8,3.3,-0.1,-0.7,5.6,-1.0,-0.2,3.9,0.4,-0.7
4,September-24,20.6,24.6,18.9,9.0,6.0,2.9,5.1,3.3,5.6,...,-0.6,3.6,-0.1,0.0,5.7,0.7,0.5,4.2,0.4,-0.4

In [288]:
x_to_predict=pd.DataFrame()

In [289]:
for party in ['Ap', 'Hoyre', 'Frp', 'SV', 'Sp', 'KrF', 'Venstre', 'MDG','Rodt', 'Andre']: 
    x_to_predict[f"{party}_prev"] = df[party]
    for t in trends:
        x_to_predict[f"{party}_trend_{t}"] = df[party] - df[party].shift(-t)

In [290]:
x_to_predict = x_to_predict.iloc[0:1]

In [291]:
x_to_predict

,Ap_prev,Ap_trend_3,Ap_trend_6,Hoyre_prev,Hoyre_trend_3,Hoyre_trend_6,Frp_prev,Frp_trend_3,Frp_trend_6,SV_prev,...,Venstre_trend_6,MDG_prev,MDG_trend_3,MDG_trend_6,Rodt_prev,Rodt_trend_3,Rodt_trend_6,Andre_prev,Andre_trend_3,Andre_trend_6
0,19.1,-0.8,-2.0,22.2,-1.2,-2.7,24.1,3.8,7.6,8.0,...,-1.1,3.3,-0.2,-0.4,5.6,-0.3,0.2,3.9,0.2,-0.8

In [293]:
df_features.to_csv("../data/featured_data.csv", sep=";")

In [295]:
x_to_predict.to_csv("../data/featured_to_predict.csv", sep=";")